### ISSUE TITLE
sintesis_abigail coronel

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-3-sintesis-abicoronel#2]
[SINTESIS DE LAS BUENAS PRACTICAS DE EN LA GESTION DE PROYECTOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-abicoronel/files/12530074/SINTESIS.DE.LAS.BUENAS.PRACTICAS.DE.EN.LA.GESTION.DE.PROYECTOS.pdf)

**Comment by EdwinOrtiz1412** [comment]
20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
